######################################################################
# Automatically generated by qmake (3.0) Mon Aug 8 21:49:36 2016
######################################################################

TEMPLATE = app
TARGET = tpm_desktop
INCLUDEPATH += . include
QT += core gui
QT += widgets


# Input
HEADERS += \
    include/mainwindow.h \
    include/ui_mainwindow.h
FORMS += \
    forms/mainwindow.ui
SOURCES += \
    src/main.cpp \
    src/mainwindow.cpp
